### ISSUE TITLE
Fail to reproduce `rel-trial`'s `study-adverse`

### ISSUE THREAD

**Issue by iloverdl** [snap-stanford/relbench#284]
The result I got is 
Best Val metrics: {''mae': np.float64(53.714) which is significantly worse than that reported in the papper (46.290)
Best test metrics: {'mae': np.float64(54.187)} which is significantly worse than that reported in the papper (44.473)

I followed the instruction on hyperparamerters as follows:
```
aggr:
    value: mean
batch_size:
    value: 512
channels:
    value: 128
dataset:
    value: rel-trial
epochs:
    value: 20
lr:
    value: 0.0001
max_steps_per_epoch:
    value: 2000
num_layers:
    value: 2
num_neighbors:
    value: 64
num_workers:
    value: 0
seed:
    value: 42
task:
    value: study-adverse
temporal_strategy:
    value: uniform
```
